---
  - name: Copy sudoers file for safety
    command: cp -f /etc/sudoers /etc/sudoers.tmp

  - name: Create sudoers file backup
    command: cp -f /etc/sudoers /etc/sudoers.bak

  - name: Create sudo group
    group: name=sudo system=yes state=present

  - name: make sure we can sudo as sudo group
    lineinfile: "dest=/etc/sudoers.tmp state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"

  - name: also make sure ssh-agent works via sudo
    lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'

  - name: Final sudoers file check
    shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
